name: wallpost
description: WallPost Mobile App

version: 3.0.4+181

environment:
  sdk: ">=2.17.0 <3.0.5"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  uuid: ^3.0.6
  data_connection_checker_tv: 0.3.5-nullsafety
  sift: 1.0.10
  encrypt: 5.0.1
  shared_preferences: 2.0.15
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  dio: ^4.0.6
  pretty_dio_logger: 1.2.0-beta-1
  flutter_keyboard_visibility: ^5.3.0
  flutter_svg: ^1.1.0
  flutter_statusbarcolor_ns: ^0.5.0
  intl: 0.17.0
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  mime_type: 1.0.0
  cached_network_image: ^3.2.1
  flutter_app_badger: ^1.4.0
  shimmer: 2.0.0
  notifiable: 1.0.6
  google_maps_flutter: ^2.1.8
  camera: ^0.10.0
  camera_avfoundation:
  path_provider:
  path:
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  fl_chart: ^0.55.1
  carousel_indicator: ^1.0.6
  url_launcher: ^6.1.5
  email_validator: ^2.1.17
  file_picker: ^5.0.1
  open_filex: ^4.0.1
  image_picker: ^0.8.5+3
  visibility_detector: ^0.3.3
  sliver_tools: ^0.2.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  mutation_test: ^1.2.2
  random_string: 2.3.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
    - family: SF-Pro-Display
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.ttf
