name: wallpost
description: WallPost Mobile App

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dartz: ^0.8.9
  uuid: ^2.0.4
  data_connection_checker: ^0.3.4
  sift:
  encrypt: ^4.0.0
  shared_preferences: ^0.5.6+3
  device_info: ^0.4.2+1
  package_info: ^0.4.0+16
  dio: ^3.0.9
  pretty_dio_logger: ^1.1.1
  provider: ^4.1.3
  keyboard_visibility: any
  flutter_svg: ^0.17.0
  image_picker: ^0.6.7+4
  modal_bottom_sheet: ^0.2.0+1
  progress_dialog: ^1.2.4
  country_list_pick: ^1.0.0+5
  flag: ^3.0.0-pre
  flutter_statusbarcolor: ^0.2.3
  country_icons: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  random_string: ^2.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: PTSans
      fonts:
        - asset: fonts/PTSans-Bold.ttf
        - asset: fonts/PTSans-BoldItalic.ttf
        - asset: fonts/PTSans-Italic.ttf
        - asset: fonts/PTSans-Regular.ttf