class Mocks {
  static Map<String, dynamic> approvalListResponse = {
    "detail": [
      {
        "id": 875,
        "company_id": 20,
        "leave_days": 1,
        "leave_from": "Aug-03-2022",
        "leave_to": "Aug-03-2022",
        "leave_from_actual": "2022-08-18",
        "leave_to_actual": "2022-08-20",
        "auto_number": "21/00875",
        "employee_id": 3157,
        "employee_name": "some employee name",
        "status": 0,
        "attach_doc": [],
        "origin": null,
        "destination": null,
        "leave_type_id": 166,
        "created_on": "31/08/2021",
        "type": "hr",
        "approve_request_by": "Adam  S",
        "decision_status": "pending",
        "reject_message": null,
        "leave_type": {
          "id": 166,
          "name": "Personal",
          "return_confirmation": "NO",
          "handover_status": "0",
          "clearance_status": 0,
          "payment_cheque_type": "0"
        }
      },
      {
        "id": 875,
        "company_id": 20,
        "leave_days": 1,
        "leave_from": "Aug-03-2022",
        "leave_to": "Aug-03-2022",
        "leave_from_actual": "2022-08-18",
        "leave_to_actual": "2022-08-20",
        "auto_number": "21/00875",
        "employee_id": 3157,
        "employee_name": "some employee name",
        "status": 0,
        "attach_doc": [],
        "origin": null,
        "destination": null,
        "leave_type_id": 166,
        "created_on": "31/08/2021",
        "type": "hr",
        "approve_request_by": "Adam  S",
        "decision_status": "pending",
        "reject_message": null,
        "leave_type": {
          "id": 166,
          "name": "Personal",
          "return_confirmation": "NO",
          "handover_status": "0",
          "clearance_status": 0,
          "payment_cheque_type": "0"
        }
      },
      {
        "id": 875,
        "company_id": 20,
        "leave_days": 1,
        "leave_from": "Aug-03-2022",
        "leave_to": "Aug-03-2022",
        "leave_from_actual": "2022-08-18",
        "leave_to_actual": "2022-08-20",
        "auto_number": "21/00875",
        "employee_id": 3157,
        "employee_name": "some employee name",
        "status": 0,
        "attach_doc": [],
        "origin": null,
        "destination": null,
        "leave_type_id": 166,
        "created_on": "31/08/2021",
        "type": "hr",
        "approve_request_by": "Adam  S",
        "decision_status": "pending",
        "reject_message": null,
        "leave_type": {
          "id": 166,
          "name": "Personal",
          "return_confirmation": "NO",
          "handover_status": "0",
          "clearance_status": 0,
          "payment_cheque_type": "0"
        }
      },
    ]
  };
}
