import 'package:random_string/random_string.dart';

class Mocks {
  static Map<String, dynamic> taskCountResponse = {
    "all": randomBetween(1000, 5000),
    "approvals": randomBetween(1000, 5000),
    "awaiting_deadline": randomBetween(1000, 5000),
    "cancelled": randomBetween(1000, 5000),
    "completed": randomBetween(1000, 5000),
    "default": randomBetween(1000, 5000),
    "draft": randomBetween(1000, 5000),
    "due_cancelled": randomBetween(1000, 5000),
    "due_completed": randomBetween(1000, 5000),
    "due_in_week": randomBetween(1000, 5000),
    "due_onhold": randomBetween(1000, 5000),
    "due_today": randomBetween(1000, 5000),
    "escalated": randomBetween(1000, 5000),
    "inprogress": randomBetween(1000, 5000),
    "new": randomBetween(1000, 5000),
    "onhold": randomBetween(1000, 5000),
    "overdue": randomBetween(1000, 5000),
    "pending": randomBetween(1000, 5000),
    "private": randomBetween(1000, 5000),
    "rejected": randomBetween(1000, 5000),
    "repeating": randomBetween(1000, 5000),
    "up_comming_dues": randomBetween(1000, 5000),
  };

  static List<Map<String, dynamic>> taskCategoriesListResponse = [
    {
      "category_id": randomString(10),
      "description": randomString(10),
      "name": randomString(10),
    },
    {
      "category_id": randomString(10),
      "description": randomString(10),
      "name": randomString(10),
    },
  ];

  static List<Map<String, dynamic>> departmentsListResponse = [
    {
      "delete_status": randomString(10),
      "description": randomString(10),
      "id": randomBetween(1000, 5000),
      "name": randomString(10),
    },
    {
      "delete_status": randomString(10),
      "description": randomString(10),
      "id": randomBetween(1000, 5000),
      "name": randomString(10),
    },
  ];

  static List<Map<String, dynamic>> taskAssigneesListResponse = [
    {
      "code": randomString(10),
      "company_id": randomBetween(1000, 5000),
      "created_at": randomBetween(1000, 5000),
      "created_by": randomString(10),
      "department": {
        "id": randomBetween(1000, 5000),
        "name": randomString(10),
      },
      "designation": {
        "id": randomBetween(1000, 5000),
        "name": randomString(10),
      },
      "email_id_office": randomString(10),
      "email_salutation": randomString(10),
      "employment_details": {
        "first_name": randomString(10),
        "full_name": randomString(10),
        "fullName": randomString(10),
        "image": randomString(10),
        "last_name": randomString(10),
        "middle_name": randomString(10),
        "user_credentials": randomString(10),
        "user_master_id": randomString(10),
      },
      "employment_id": randomString(10),
      "id": randomBetween(1000, 5000),
      "join_date": randomString(10),
      "line_manager": randomString(10),
      "old_table_ref": randomBetween(1000, 5000),
      "profile_image": randomString(10),
      "signature": randomString(10),
      "status": randomString(10),
      "triggered": randomString(10),
      "updated_at": randomBetween(1000, 5000),
      "user_master_id": randomString(10),
    },
    {
      "code": randomString(10),
      "company_id": randomBetween(1000, 5000),
      "created_at": randomBetween(1000, 5000),
      "created_by": randomString(10),
      "department": {
        "id": randomBetween(1000, 5000),
        "name": randomString(10),
      },
      "designation": {
        "id": randomBetween(1000, 5000),
        "name": randomString(10),
      },
      "email_id_office": randomString(10),
      "email_salutation": randomString(10),
      "employment_details": {
        "first_name": randomString(10),
        "full_name": randomString(10),
        "fullName": randomString(10),
        "image": randomString(10),
        "last_name": randomString(10),
        "middle_name": randomString(10),
        "user_credentials": randomString(10),
        "user_master_id": randomString(10),
      },
      "employment_id": randomString(10),
      "id": randomBetween(1000, 5000),
      "join_date": randomString(10),
      "line_manager": randomString(10),
      "old_table_ref": randomBetween(1000, 5000),
      "profile_image": randomString(10),
      "signature": randomString(10),
      "status": randomString(10),
      "triggered": randomString(10),
      "updated_at": randomBetween(1000, 5000),
      "user_master_id": randomString(10),
    },
  ];

  static List<Map<String, dynamic>> tasksListResponse = [
    {
      "alloted_asset": randomString(10),
      "allottee": randomString(10),
      "approval_comment": randomString(10),
      "approval_id": randomString(10),
      "approval_name": randomString(10),
      "approval_requested_at": randomString(10),
      "approver_id": randomString(10),
      "approver_sub_type": randomString(10),
      "asset_type": randomString(10),
      "assignee_EmailID": randomString(10),
      "assignee_fullName": randomString(10),
      "assignee_gender": randomString(10),
      "assignee_line_manager_employment_id": randomString(10),
      "assignee_line_manager_fullName": randomString(10),
      "assignees": [
        {
          "employee": {
            "department": {
              "id": randomBetween(1000, 5000),
              "name": randomString(10),
            },
            "designation": {
              "id": randomBetween(1000, 5000),
              "name": randomString(10),
            },
            "email_id_office": randomString(10),
            "email_salutation": randomString(10),
            "employment_details": {
              "first_name": randomString(10),
              "full_name": randomString(10),
              "fullName": randomString(10),
              "image": randomString(10),
              "last_name": randomString(10),
              "middle_name": randomString(10),
              "user_master_id": randomString(10),
            },
            "employment_id": randomString(10),
            "id": randomBetween(1000, 5000),
            "line_manager": randomString(10),
            "profile_image": randomString(10),
            "user_master_id": randomString(10),
          },
          "status": randomString(10),
          "task_id": randomString(10),
        },
      ],
      "attachment_req": true,
      "attempt_extension_date": randomString(10),
      "attempt_extension_reason": randomString(10),
      "attempt_reassign_reason": randomString(10),
      "attempt_reassignee": randomString(10),
      "category": randomString(10),
      "category_id": randomString(10),
      "company_id": randomBetween(1000, 5000),
      "created_at": randomString(10),
      "created_by": {
        "department": {
          "id": randomBetween(1000, 5000),
          "name": randomString(10),
        },
        "designation": {
          "id": randomBetween(1000, 5000),
          "name": randomString(10),
        },
        "email_id_office": randomString(10),
        "email_salutation": randomString(10),
        "employment_details": {
          "first_name": randomString(10),
          "full_name": randomString(10),
          "fullName": randomString(10),
          "image": randomString(10),
          "last_name": randomString(10),
          "middle_name": randomString(10),
          "user_master_id": randomString(10),
        },
        "employment_id": randomString(10),
        "profile_image": randomString(10),
        "user_master_id": randomString(10),
      },
      "deleted_at": randomString(10),
      "description": randomString(10),
      "end_time": randomString(10),
      "escalated_at": randomString(10),
      "escalated_to_fullName": randomString(10),
      "escalated_until": randomString(10),
      "files": [
        randomString(10),
        randomString(10),
        randomString(10),
      ],
      "freez_type": randomString(10),
      "id": randomBetween(1000, 5000),
      "is_draft": true,
      "is_escalated": 1,
      "is_frozen": true,
      "is_private": true,
      "latest_approval_action_taker_fullName": randomString(10),
      "latest_approval_date": randomString(10),
      "latest_approval_reason": randomString(10),
      "latest_approval_status": randomString(10),
      "name": randomString(10),
      "notification": [
        randomString(10),
        randomString(10),
        randomString(10),
      ],
      "old_table_ref": randomBetween(1000, 5000),
      "parent_task": randomString(10),
      "progress_percentage": true,
      "reassignee_assignee_fullName": randomString(10),
      "schedule": {
        "completed_at": randomString(10),
        "delayed_in_days": randomString(10),
        "delayed_in_minutes": randomString(10),
        "due_in_days": randomBetween(1000, 5000),
        "duration": randomBetween(1000, 5000),
        "end_date": '2020-10-30',
        "end_time": '17:00:00',
        "extended_date": randomString(10),
        "extended_reason": randomString(10),
        "extended_time": randomString(10),
        "is_completed": true,
        "is_repeating": true,
        "onhold_date": randomString(10),
        "recurrence_parent": randomString(10),
        "rrule": {
          "byday": randomString(10),
          "dtstart": randomString(10),
          "freq": randomString(10),
          "interval": randomString(10),
          "until": randomString(10),
          "wkst": randomString(10),
        },
        "rrule_string": randomString(10),
        "start_date": '2020-10-20',
        "start_time": '09:00:00',
        "task_id": randomString(10),
        "timezone": randomString(10),
      },
      "start_time": randomString(10),
      "status": {
        "display_name": randomString(10),
        "name": randomString(10),
        "status_id": randomBetween(1000, 5000),
      },
      "status_id": randomBetween(1000, 5000),
      "sub_tasks": [
        randomString(10),
        randomString(10),
        randomString(10),
      ],
      "task_approval_applayer": randomString(10),
      "task_approval_applayer_fullName": randomString(10),
      "task_approval_approver_fullName": randomString(10),
      "task_approver_fullName": randomString(10),
      "task_creator_EmailID": randomString(10),
      "task_creator_fullName": randomString(10),
      "task_id": randomString(10),
      "task_no": randomString(10),
      "task_owner": randomString(10),
      "task_owner_EmailID": randomString(10),
      "task_owner_fullName": randomString(10),
      "updated_at": randomString(10),
    },
  ];

  static Map<String, dynamic> taskTimeZonesResponse = {'timezones':[
    randomString(10),
    randomString(10),
    randomString(10),
  ]};

  static Map<String, dynamic> createTaskResponse = {
    "alloted_asset": randomString(10),
    "allottee": randomString(10),
    "approval_comment": randomString(10),
    "approval_id": randomString(10),
    "approval_name": randomString(10),
    "approval_requested_at": randomString(10),
    "approver_id": randomString(10),
    "approver_sub_type": randomString(10),
    "asset_type": randomString(10),
    "assignee_EmailID": randomString(10),
    "assignee_fullName": randomString(10),
    "assignee_gender": randomString(10),
    "assignee_line_manager_employment_id": randomString(10),
    "assignee_line_manager_fullName": randomString(10),
    "assignees": [
      {
        "employee": randomString(10),
        "status": randomString(10),
        "task_id": randomString(10),
      },
    ],
    "attachment_req": true,
    "attempt_extension_date": randomString(10),
    "attempt_extension_reason": randomString(10),
    "attempt_reassign_reason": randomString(10),
    "attempt_reassignee": randomString(10),
    "category": randomString(10),
    "category_id": randomString(10),
    "company_id": true,
    "created_at": randomString(10),
    "created_by": {
      "department": {
        "id": randomBetween(1000, 5000),
        "name": randomString(10),
      },
      "designation": {
        "id": randomBetween(1000, 5000),
        "name": randomString(10),
      },
      "email_id_office": randomString(10),
      "email_salutation": randomString(10),
      "employment_details": {
        "first_name": randomString(10),
        "full_name": randomString(10),
        "fullName": randomString(10),
        "image": randomString(10),
        "last_name": randomString(10),
        "middle_name": randomString(10),
        "user_master_id": randomString(10),
      },
      "employment_id": randomString(10),
      "profile_image": randomString(10),
      "user_master_id": randomString(10),
    },
    "deleted_at": randomString(10),
    "description": randomString(10),
    "end_time": randomString(10),
    "escalated_at": randomString(10),
    "escalated_to_fullName": randomString(10),
    "escalated_until": randomString(10),
    "files": [
      randomString(10),
      randomString(10),
      randomString(10),
    ],
    "freez_type": randomString(10),
    "id": randomBetween(1000, 5000),
    "is_draft": true,
    "is_escalated": true,
    "is_frozen": true,
    "is_private": true,
    "latest_approval_action_taker_fullName": randomString(10),
    "latest_approval_date": randomString(10),
    "latest_approval_reason": randomString(10),
    "latest_approval_status": randomString(10),
    "name": randomString(10),
    "notification": [
      randomString(10),
      randomString(10),
      randomString(10),
    ],
    "old_table_ref": randomBetween(1000, 5000),
    "parent_task": randomString(10),
    "progress_percentage": true,
    "reassignee_assignee_fullName": randomString(10),
    "schedule": {
      "completed_at": randomString(10),
      "delayed_in_days": randomString(10),
      "delayed_in_minutes": randomString(10),
      "due_in_days": randomBetween(1000, 5000),
      "duration": true,
      "end_date": randomString(10),
      "end_time": randomString(10),
      "extended_date": randomString(10),
      "extended_reason": randomString(10),
      "extended_time": randomString(10),
      "is_completed": true,
      "is_repeating": true,
      "onhold_date": randomString(10),
      "recurrence_parent": randomString(10),
      "rrule": randomString(10),
      "rrule_string": randomString(10),
      "start_date": randomString(10),
      "start_time": randomString(10),
      "task_id": randomString(10),
      "timezone": randomString(10),
    },
    "start_time": randomString(10),
    "status": {
      "display_name": randomString(10),
      "name": randomString(10),
      "status_id": randomBetween(1000, 5000),
    },
    "status_id": randomBetween(1000, 5000),
    "sub_tasks": [
      randomString(10),
      randomString(10),
      randomString(10),
    ],
    "task_approval_applayer": randomString(10),
    "task_approval_applayer_fullName": randomString(10),
    "task_approval_approver_fullName": randomString(10),
    "task_approver_fullName": randomString(10),
    "task_creator_EmailID": randomString(10),
    "task_creator_fullName": randomString(10),
    "task_id": randomString(10),
    "task_no": randomString(10),
    "task_owner": randomString(10),
    "task_owner_EmailID": randomString(10),
    "task_owner_fullName": randomString(10),
    "updated_at": randomString(10),
  };
}
