class Mocks {
  static List<Map<String, dynamic>> approvalListResponse = [
    {
      "bill_id": 2005,
      "supplier_name": "Kiran",
      "bill_number": "22\/00024",
      "bill_date": "2022-02-01",
      "due_date": "2022-02-01",
      "profile_photo": null,
      "amount": 2997.9,
      "supplier_id": 188,
      "currency": "KWD",
      "requested_by": 277,
      "app_type": "billRequest",
      "type": "finance",
      "company_id": 19,
      "decision_status": "pending",
      "reject_message": null,
      "payment_status": "Unpaid"
      },
      {
        "bill_id": 2006,
        "supplier_name": "Kiran",
        "bill_number": "22\/00024",
        "bill_date": "2022-02-01",
        "due_date": "2022-02-01",
        "profile_photo": null,
        "amount": 2997.9,
        "supplier_id": 188,
        "currency": "KWD",
        "requested_by": 277,
        "app_type": "billRequest",
        "type": "finance",
        "company_id": 19,
        "decision_status": "pending",
        "reject_message": null,
        "payment_status": "Unpaid"
      },
      {
        "bill_id": 2007,
        "supplier_name": "Kiran",
        "bill_number": "22\/00024",
        "bill_date": "2022-02-01",
        "due_date": "2022-02-01",
        "profile_photo": null,
        "amount": 2997.9,
        "supplier_id": 188,
        "currency": "KWD",
        "requested_by": 277,
        "app_type": "billRequest",
        "type": "finance",
        "company_id": 19,
        "decision_status": "pending",
        "reject_message": null,
        "payment_status": "Unpaid"
      },
      {
        "bill_id": 2009,
        "supplier_name": "Kiran",
        "bill_number": "22\/00024",
        "bill_date": "2022-02-01",
        "due_date": "2022-02-01",
        "profile_photo": null,
        "amount": 2997.9,
        "supplier_id": 188,
        "currency": "KWD",
        "requested_by": 277,
        "app_type": "billRequest",
        "type": "finance",
        "company_id": 19,
        "decision_status": "pending",
        "reject_message": null,
        "payment_status": "Unpaid"
      },
      {
        "bill_id": 2010,
        "supplier_name": "Kiran",
        "bill_number": "22\/00024",
        "bill_date": "2022-02-01",
        "due_date": "2022-02-01",
        "profile_photo": null,
        "amount": 2997.9,
        "supplier_id": 188,
        "currency": "KWD",
        "requested_by": 277,
        "app_type": "billRequest",
        "type": "finance",
        "company_id": 19,
        "decision_status": "pending",
        "reject_message": null,
        "payment_status": "Unpaid"
      },
      {
        "bill_id": 2011,
        "supplier_name": "Kiran",
        "bill_number": "22\/00024",
        "bill_date": "2022-02-01",
        "due_date": "2022-02-01",
        "profile_photo": null,
        "amount": 2997.9,
        "supplier_id": 188,
        "currency": "KWD",
        "requested_by": 277,
        "app_type": "billRequest",
        "type": "finance",
        "company_id": 19,
        "decision_status": "pending",
        "reject_message": null,
        "payment_status": "Unpaid"
      }
      ];

}
