import 'package:random_string/random_string.dart';

class Mocks {
  static List<Map<String, dynamic>> companiesListResponse = [
    {
      "company_id": randomBetween(1000, 5000),
      "company_name": randomString(10),
      "currency": randomString(10),
      "notifications": randomBetween(1000, 5000),
      "actual_revenue_display": randomString(10),
      "overall_revenue": randomBetween(1000, 5000),
      "approval_count": randomBetween(1000, 5000),
    },
    {
      "company_id": randomBetween(1000, 5000),
      "company_name": randomString(10),
      "currency": randomString(10),
      "notifications": randomBetween(1000, 5000),
      "actual_revenue_display": randomString(10),
      "overall_revenue": randomBetween(1000, 5000),
      "approval_count": randomBetween(1000, 5000),
    },
    {
      "company_id": randomBetween(1000, 5000),
      "company_name": randomString(10),
      "currency": randomString(10),
      "notifications": randomBetween(1000, 5000),
      "actual_revenue_display": randomString(10),
      "overall_revenue": randomBetween(1000, 5000),
      "approval_count": randomBetween(1000, 5000),
    },
  ];

  static Map<String, dynamic> companyDetailsResponse = {
    "absolute_upload_path": randomString(10),
    "account_no": randomBetween(1000, 5000),
    "commercial_name": randomString(10),
    "company_id": randomBetween(1000, 5000),
    "company_info": {
      "allowed_radius": randomBetween(1000, 5000),
      "approval_flow_settings": true,
      "calendar_settings": true,
      "change_company": true,
      "change_user": true,
      "client_auth_key": randomString(10),
      "company_name": randomString(10),
      "company_settings": true,
      "currency": randomString(10),
      "date_format": randomString(10),
      "date_separator": randomString(10),
      "date_time_settings": true,
      "employee_user_manager": true,
      "erp_access": randomString(10),
      "external_account_settings": true,
      "fullName": randomString(10),
      "has_signature": true,
      "is_trial": 'true',
      "js_date_format": randomString(10),
      "manage_wallpost": true,
      "packages": {
        "crm": {
          "features": randomString(10),
          "package": randomString(10),
          "users": randomString(10),
        },
        "finance": {
          "features": randomString(10),
          "package": randomString(10),
          "users": randomString(10),
        },
        "hr": {
          "features": randomString(10),
          "package": randomString(10),
          "users": randomString(10),
        },
        "performance": {
          "features": randomString(10),
          "package": randomString(10),
          "users": randomString(10),
        },
        "task": {
          "features": randomString(10),
          "package": randomString(10),
          "users": randomString(10),
        },
      },
      "pricing_url": randomString(10),
      "profile_image": randomString(10),
      "report_settings": true,
      "salutation": randomString(10),
      "setup_link": true,
      "show_calender_icon": true,
      "show_timesheet_icon": true,
      "switch_account": true,
      "time_zone": randomString(10),
      "user_id": randomString(10),
      "user_manager": true,
    },
    "company_logo": randomString(10),
    "company_name": randomString(10),
    "department_rank": {
      "out_of": randomBetween(1000, 5000),
      "rank": randomBetween(1000, 5000),
    },
    "employee": {
      "designation": randomString(10),
      "email_id_office": randomString(10),
      "employment_id": randomString(10),
      "employment_id_v1": randomBetween(1000, 5000),
      "image": randomString(10),
      "line_manager": randomString(10),
      "name": randomString(10),
      "Roles": [
        randomString(10),
        randomString(10),
        randomString(10),
      ],
    },
    "general_manager": randomBetween(1000, 5000),
    "owners": randomString(10),
    "packages": [
      randomString(10),
      randomString(10),
      randomString(10),
    ],
    "payroll_wps_supported": true,
    "show_revenue": 0,
    "short_name": randomString(10),
  };
}
