
class Mocks {
  static Map<String, dynamic> attendanceListResponse = {
    "data": [
      {
        "id": "401",
        "company_id": 15,
        "attendance_id": "mua8lqhCQE6SyIz",
        "date": "2022-01-28",
        "adjusted_status": "PRESENT",
        "punch_in_time": "09:00",
        "punch_out_time": "06:00",
        "orig_punch_in_time": null,
        "orig_punch_out_time": null,
        "reason": "forgot to punch",
        "approval_status": "Pending",
        "approver_name": "Jayden Mathew"
      },
      {
        "id": "402",
        "company_id": 15,
        "attendance_id": "c8VDE2Scvd9lilI",
        "date": "2022-01-25",
        "adjusted_status": "PRESENT",
        "punch_in_time": "10:15",
        "punch_out_time": "06:00",
        "orig_punch_in_time": null,
        "orig_punch_out_time": null,
        "reason": "forget",
        "approval_status": "Pending",
        "approver_name": "Jayden Mathew"
      },
      {
        "id": "403",
        "company_id": 15,
        "attendance_id": "nnIalwBedW3U4Wg",
        "date": "2022-01-24",
        "adjusted_status": "PRESENT",
        "punch_in_time": "08:00",
        "punch_out_time": "03:00",
        "orig_punch_in_time": null,
        "orig_punch_out_time": null,
        "reason": "kkkkkkkkkkkkkkkkkkkk",
        "approval_status": "Pending",
        "approver_name": "Jayden Mathew"
      },
      {
        "id": "404",
        "company_id": 15,
        "attendance_id": "GAlgrqH5NsHqLaH",
        "date": "2022-01-21",
        "adjusted_status": "EARLYLEAVE",
        "punch_in_time": "11:00",
        "punch_out_time": "15:30",
        "orig_punch_in_time": null,
        "orig_punch_out_time": null,
        "reason": "llllll",
        "approval_status": "Pending",
        "approver_name": "Jayden Mathew"
      },
      {
        "attendance_id": null,
        "date": "2022-01-03",
        "work_status": "ABSENT",
        "punch_in_time": null,
        "punch_out_time": null,
        "reason": null,
        "approval_status": "null"
      }
    ],
  };

  static Map<String, dynamic> attendanceListItemResponse = {
    "id": null,
    "company_id": 42,
    "attendance_id": "Q8pyUr23o8kuGJw",
    "date": "2022-01-28",
    "adjusted_status": "PRESENT",
    "punch_in_time": "08:47",
    "punch_out_time": "18:00",
    "orig_punch_in_time": "08:47",
    "orig_punch_out_time": "18:00",
    "reason": null,
    "approval_status": "null",
    "approver_name": "null"
  };

  static var submitAdjustmentHeader = [
    {
      "id": null,
      "company_id": 15,
      "attendance_id": "qpxroNBXQKgL7QW",
      "date": "2022-01-31",
      "adjusted_status": "PRESENT",
      "punch_in_time": "09:05",
      "punch_out_time": "17:30",
      "orig_punch_in_time": "11:05",
      "orig_punch_out_time": "11:13",
      "reason": "reasonnnn",
      "approval_status": "null",
      "approver_name": "null",
      "edit_mode": false,
      "punch_in_time_error": false,
      "punch_out_time_error": false,
      "status_out_error": false,
      "attnce_reason_error": false,
      "employee_id": 1254,
      "work_status": "PRESENT",
      "adjusted_punchin": "9:05",
      "adjusted_punchout": "17:30"
    }
  ];
}


/*
  {
        "attendance_id": null,
        "date": "2022-01-31",
        "work_status": "ABSENT",
        "punch_in_time": null,
        "punch_out_time": null,
        "reason": null,
        "approval_status": "null"

      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "kgx9oROVnhgJsgQ",
        "date": "2022-01-28",
        "adjusted_status": "PRESENT",
        "punch_in_time": "09:06",
        "punch_out_time": "18:10",
        "orig_punch_in_time": "09:06",
        "orig_punch_out_time": "18:10",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "ZF0KXfCk00IV68o",
        "date": "2022-01-27",
        "adjusted_status": "PRESENT",
        "punch_in_time": "08:50",
        "punch_out_time": "18:05",
        "orig_punch_in_time": "08:50",
        "orig_punch_out_time": "18:05",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "2b6Dr03o4iZpg9J",
        "date": "2022-01-25",
        "adjusted_status": "PRESENT",
        "punch_in_time": "09:07",
        "punch_out_time": "18:18",
        "orig_punch_in_time": "09:07",
        "orig_punch_out_time": "18:18",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "v39fDmh9gz5DSpy",
        "date": "2022-01-24",
        "adjusted_status": "PRESENT",
        "punch_in_time": "08:49",
        "punch_out_time": "18:15",
        "orig_punch_in_time": "08:49",
        "orig_punch_out_time": "18:15",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "nJgR2fUV8Lv7Y2L",
        "date": "2022-01-21",
        "adjusted_status": "PRESENT",
        "punch_in_time": "08:54",
        "punch_out_time": "18:11",
        "orig_punch_in_time": "08:54",
        "orig_punch_out_time": "18:11",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "Fpz0QIhlU42HNY2",
        "date": "2022-01-20",
        "adjusted_status": "EARLYLEAVE",
        "punch_in_time": "08:55",
        "punch_out_time": "18:30",
        "orig_punch_in_time": "08:55",
        "orig_punch_out_time": "18:30",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "7rK3ssBBceVSYb5",
        "date": "2022-01-19",
        "adjusted_status": "EARLYLEAVE",
        "punch_in_time": "10:10",
        "punch_out_time": "18:30",
        "orig_punch_in_time": "10:10",
        "orig_punch_out_time": "18:30",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "3kn5VZ2Pcv7RAn8",
        "date": "2022-01-18",
        "adjusted_status": "PRESENT",
        "punch_in_time": "08:34",
        "punch_out_time": "18:18",
        "orig_punch_in_time": "08:34",
        "orig_punch_out_time": "18:18",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "MMpiEn799K3P887",
        "date": "2022-01-17",
        "adjusted_status": "PRESENT",
        "punch_in_time": "08:36",
        "punch_out_time": "18:04",
        "orig_punch_in_time": "08:36",
        "orig_punch_out_time": "18:04",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "ItnWKWEOpSMnSUj",
        "date": "2022-01-14",
        "adjusted_status": "LATE",
        "punch_in_time": "09:19",
        "punch_out_time": "18:05",
        "orig_punch_in_time": "09:19",
        "orig_punch_out_time": "18:05",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "uu6VwX0Jnxmp5Hz",
        "date": "2022-01-12",
        "adjusted_status": "PRESENT",
        "punch_in_time": "09:05",
        "punch_out_time": "18:26",
        "orig_punch_in_time": "09:05",
        "orig_punch_out_time": "18:26",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "FQ33WuuagN5HSL0",
        "date": "2022-01-11",
        "adjusted_status": "EARLYLEAVE",
        "punch_in_time": "09:53",
        "punch_out_time": "18:30",
        "orig_punch_in_time": "09:53",
        "orig_punch_out_time": "18:30",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "hCM7TXkC8BNLl5m",
        "date": "2022-01-10",
        "adjusted_status": "PRESENT",
        "punch_in_time": "08:34",
        "punch_out_time": "18:27",
        "orig_punch_in_time": "08:34",
        "orig_punch_out_time": "18:27",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "6f19ZjQCOZku7ix",
        "date": "2022-01-07",
        "adjusted_status": "EARLYLEAVE",
        "punch_in_time": "08:30",
        "punch_out_time": "18:30",
        "orig_punch_in_time": "08:30",
        "orig_punch_out_time": "18:30",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "ibEANG1Luf3AQWZ",
        "date": "2022-01-06",
        "adjusted_status": "PRESENT",
        "punch_in_time": "08:41",
        "punch_out_time": "18:29",
        "orig_punch_in_time": "08:41",
        "orig_punch_out_time": "18:29",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "FkfGitd3vnoXis0",
        "date": "2022-01-05",
        "adjusted_status": "LATE",
        "punch_in_time": "09:39",
        "punch_out_time": "18:28",
        "orig_punch_in_time": "09:39",
        "orig_punch_out_time": "18:28",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "id": null,
        "company_id": 42,
        "attendance_id": "QjkVdowRXoh0E9b",
        "date": "2022-01-04",
        "adjusted_status": "LATE",
        "punch_in_time": "09:21",
        "punch_out_time": "18:02",
        "orig_punch_in_time": "09:21",
        "orig_punch_out_time": "18:02",
        "reason": null,
        "approval_status": "null",
        "approver_name": "null"
      },
      {
        "attendance_id": null,
        "date": "2022-01-03",
        "work_status": "ABSENT",
        "punch_in_time": null,
        "punch_out_time": null,
        "reason": null,
        "approval_status": "null"
      }
 */
