import 'package:random_string/random_string.dart';

class Mocks {
  static List<Map<String, dynamic>> leaveListResponse = [
    {
      "air_class": randomString(10),
      "approval_comments": randomString(10),
      "attach_doc": [
        {
          "attachment": randomString(10),
          "company_id": randomBetween(1000, 5000),
          "document_file_name": randomString(10),
          "reference_id": randomBetween(1000, 5000),
        },
      ],
      "auto_number": randomString(10),
      "cancel_reason": randomString(10),
      "clearance_status": randomString(10),
      "company_id": randomBetween(1000, 5000),
      "contact_email": randomString(10),
      "contact_on_leave": randomString(10),
      "created_on": randomString(10),
      "decision_status": randomString(10),
      "departure_date": randomString(10),
      "departure_time": randomString(10),
      "destination": randomString(10),
      "employee": {
        "active": randomString(10),
        "code": randomString(10),
        "company": randomBetween(1000, 5000),
        "department": {
          "id": randomBetween(1000, 5000),
          "name": randomString(10),
        },
        "designation": randomBetween(1000, 5000),
        "email_cc": randomString(10),
        "email_id_office": randomString(10),
        "email_salutation": randomString(10),
        "employee_grade": randomBetween(1000, 5000),
        "fullName": randomString(10),
        "gender": randomString(10),
        "id": randomBetween(1000, 5000),
        "join_date": randomString(10),
        "line_manager": randomBetween(1000, 5000),
        "middle_name": randomString(10),
        "name": randomString(10),
        "photo": randomString(10),
        "position": {
          "id": randomBetween(1000, 5000),
          "name": randomString(10),
        },
        "profile_image": randomString(10),
        "short_name": randomString(10),
        "signature": randomString(10),
        "sponser_name": randomString(10),
        "username": randomString(10),
      },
      "employee_id": randomBetween(1000, 5000),
      "exit_required": true,
      "extra_info": {
        "handover": {
          "action": randomString(10),
          "status": randomString(10),
        },
      },
      "family_ticket": randomString(10),
      "handover_status": randomString(10),
      "id": randomBetween(1000, 5000),
      "leave_days": randomBetween(1000, 5000),
      "leave_from": '2020-12-01',
      "leave_reason": randomString(10),
      "leave_to": "2020-12-20",
      "leave_type": {
        "clearance_status": true,
        "handover_status": randomString(10),
        "id": randomBetween(1000, 5000),
        "name": randomString(10),
        "payment_cheque_type": randomString(10),
      },
      "leave_type_id": randomBetween(1000, 5000),
      "no_ticket_adult": true,
      "no_ticket_children": true,
      "origin": randomString(10),
      "paid_days": randomBetween(1000, 5000),
      "rejected_at": randomString(10),
      "rejected_by": randomString(10),
      "rejected_reason": randomString(10),
      "replaced_by": randomString(10),
      "replaced_by_others": randomString(10),
      "replaced_required": randomString(10),
      "return_date": randomString(10),
      "return_time": randomString(10),
      "status": 0,
      "ticket": randomString(10),
      "unpaid_days": true,
      "voucher": randomString(10),
      "way_type": randomString(10),
    },
  ];

  static Map<String, dynamic> leaveTypesResponse = {
    "airportDetails": randomString(10),
    "exitPermit": true,
    "joining_date": randomString(10),
    "leaveTicket": true,
    "leaveTypes": [
      {
        "code": randomString(10),
        "id": randomBetween(1000, 5000),
        "leaveType": randomBetween(1000, 5000),
        "min_period": randomBetween(1000, 5000),
        "name": randomString(10),
        "pay_items": randomString(10),
        "requires_certificate": "1",
      },
      {
        "code": randomString(10),
        "id": randomBetween(1000, 5000),
        "leaveType": randomBetween(1000, 5000),
        "min_period": randomBetween(1000, 5000),
        "name": randomString(10),
        "pay_items": randomString(10),
        "requires_certificate": "0",
      },
      {
        "code": randomString(10),
        "id": randomBetween(1000, 5000),
        "leaveType": randomBetween(1000, 5000),
        "min_period": randomBetween(1000, 5000),
        "name": randomString(10),
        "pay_items": randomString(10),
        "requires_certificate": "1",
      },
      {
        "code": randomString(10),
        "id": randomBetween(1000, 5000),
        "leaveType": randomBetween(1000, 5000),
        "min_period": randomBetween(1000, 5000),
        "name": randomString(10),
        "pay_items": randomString(10),
        "requires_certificate": "1",
      },
    ],
    "ticketDetails": {},
  };
}
